name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - '*'
    exclude:
    - /tools/releaseBuild/**/*
    - /.vsts-ci/misc-analysis.yml
    - /.github/ISSUE_TEMPLATE/*
pr:
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - '*'
    exclude:
    - /tools/releaseBuild/**/*
    - /.vsts-ci/misc-analysis.yml
    - /.github/ISSUE_TEMPLATE/*
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

resources:
- repo: self
  clean: true
jobs:
- template: templates/ci-build.yml
  parameters:
    pool: Hosted Ubuntu 1604
    jobName: linux_build
    displayName: linux Build

- template: templates/nix-test.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    purpose: UnelevatedPesterTests
    tagSet: CI
    parentJobs:
      - linux_build

- template: templates/nix-test.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    purpose: ElevatedPesterTests
    tagSet: CI
    parentJobs:
      - linux_build

- template: templates/nix-test.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    purpose: UnelevatedPesterTests
    tagSet: Others
    parentJobs:
      - linux_build

- template: templates/nix-test.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    purpose: ElevatedPesterTests
    tagSet: Others
    parentJobs:
      - linux_build

- template: templates/verify-xunit.yml
  parameters:
    pool: Hosted Ubuntu 1604
    dependsOn: linux_build
